<?php
/**
 * Return the default options of the theme
 * 
 * @return  void
 */

function themesflat_customize_default($key) {
	$default = array(
		'social_links'	=> array ("facebook" => '#', "twitter" => '#', "instagram" => '#', "pinterest"  => '#'),
		'show_social_share' => 0,		
		'social_footer' => 0,
		'go_top' => 1,
		'topbar_background_color'	=> '#f7f0ea',
		'topbar_textcolor'	=> '#798883',
		'topbar_link_color' => '#798883',
		'topbar_link_color_hover' => '#e6d54f',
		'topbar_show' => 0 ,
		'topbar_address_label' => '<i class="icon-graingrow-grow1"></i>',
		'topbar_address' => 'Have a Question? Call+1 (888) 123-4567',
		'topbar_email_label' => '<i class="icon-graingrow-grow2"></i>',
		'topbar_email' => 'Email: com@exam.com',
		'social_topbar' => 0,
		'typography_topbar' => array(
			'family' => 'Poppins',
			'style'  => '400',
			'size'   => '15',
			'line_height'=>'1.8666666666666667',
			'letter_spacing' => '',
		),
		'topbar_controls' => array('padding-top' => 0,'padding-bottom' => 0),
		'logo_controls' => array('padding-top' => '','padding-bottom' => ''),
		'style_header'	=> 'header-default',	
		'header_backgroundcolor'=>'#fff',
		'header_sticky' => 0,
		'header_search_box' => 0,
		'header_content_right' => '',
		'header_absolute'	=> 1,		
		'header_sidebar_toggler' => 0,
		'header_button_show' => 1,
		'header_button_text' => 'Get A Quote',
		'header_button_url' => '/contact',
		'header_info_phone_text' => 'Telk With Us',
		'header_info_phone_number' => '+012 (345) 6789',
		'header_cart_icon' => 0,
		'header_wishlist_icon' => 0,
		'show_post_navigator' => 0,
		'show_entry_footer_content'	=> 0,
		'logo_width' => 181,
		'menu_location_primary' => 'primary',
		'site_logo'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_mobile'	=> THEMESFLAT_LINK . 'images/logo.png',	
		'show_bottom' => 1,		
		'text_loadmore' => 'Load More',		
		'header_backgroundcolor_sticky'=>'#fff',		
		'primary_color'=>'#435a52',
		'secondary_color'=>'#297d53',
		'accent_color'=>'#e6d54f',
		'typography_body' => array(
			'family' => 'Poppins',
			'style'  => 'regular',
			'size'   => '16',
			'line_height'=>'1.75',
			'letter_spacing' => '0px',
		),
		'body_text_color'=>'#494A4D',
		'body_background_color' => '',
		'page_sidebar_layout' => 'fullwidth',
		'content_controls' => array('padding-top' => 100,'padding-bottom' => 100),
		'typography_menu' => array(
			'family' => 'Outfit',
			'style'  => '600',
			'size'   => '18',
			'line_height'=>'23px',
			'letter_spacing' => '0px',
		), 
		'mainnav_color'		=> '#3e483c',
		'mainnav_hover_color'=>'#297d53',
		'mainnav_active_color'=>'#297d53',
		'menu_distance_between' => 10,
		'typography_sub_menu' => array(
			'family' => 'Outfit',
			'style'  => '600',
			'size'   => '18',
			'line_height'=>'26px',
			'letter_spacing' => '0px',
		),
		'sub_nav_color'		=>'#3e483c',		
		'sub_nav_color_hover'	=>	'#297d53',
		'sub_nav_background'=>'#ffffff',
		'sub_nav_background_hover'=>'rgba(255,255,255,0)',
		'sub_nav_border_color' => '#E8E8E9',
		'typography_headings'	=> array(
			'family' => 'Outfit',
			'style'  => '700',
			'line_height'=>'1.333',
			'letter_spacing' => '0px'		
		),
		'h1_size' => 50,
		'h2_size' => 32,
		'h3_size' => 28,
		'h4_size' => 24,
		'h5_size' => 20,
		'h6_size' => 16,
		'typography_blockquote' => array(
			'family' => 'Outfit',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'30px',
			'letter_spacing' => '0px',
		),	
		'typography_blog_post_title' => array(
			'family' => 'Nunito',
			'style'  => '700',
			'size'   => '32',
			'line_height'=>'1.2',
			'letter_spacing' => '',
		),
		'typography_blog_post_meta' => array(
			'family' => 'Open Sans',
			'style'  => '400',
			'size'   => '12',
			'line_height'=>'1.142',
			'letter_spacing' => '0px',
		),
		'typography_blog_post_buttons' => array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '16',
			'line_height'=>'1',
			'letter_spacing' => '0px',
		),
		'typography_blog_single_title' => array(
			'family' => 'Outfit',
			'style'  => '600',
			'size'   => '35',
			'line_height'=>'1.2571428571428571',
			'letter_spacing' => '-0.02em',
		),
		'typography_blog_single_comment_title' => array(
			'family' => 'Outfit',
			'style'  => '600',
			'size'   => '24',
			'line_height'=>'1',
			'letter_spacing' => '0px',
		),
		'typography_sidebar_widget_title' => array(
			'family' => 'Nunito',
			'style'  => '700',
			'size'   => '24',
			'line_height'=>'1.25',
			'letter_spacing' => '0px',
		),	
		'typography_footer_widget_title' => array(
			'family' => 'Poppins',
			'style'  => '600',
			'size'   => '18',
			'line_height'=>'1.6666666666666667',
			'letter_spacing' => '0px',
		),	
		'typography_page_title'	=> array(
			'family' => 'Outfit',
			'style'  => '600',
			'size'   => '55',
			'line_height'=>'1.18',
			'letter_spacing' => '-0.02em',
		),
		'page_title_background_color' => '#5a6259',
		'page_title_background_color_opacity' => '70',
		'page_title_text_color' => '#fff',		
		'page_title_controls' => array('padding-top' => 246, 'padding-bottom' => 162),
		'page_title_background_image' => '',
		'page_title_image_size' => 'cover',
		'page_title_heading_enabled' => 1,
		'typography_breadcrumb'	=> array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '18',
			'line_height'=>'1.55',
			'letter_spacing' => '0px',
		),
		'bread_crumb_prefix' =>'',
		'breadcrumb_separator' =>  '',
		'breadcrumb_color' => '#fff',
		'typography_buttons' => array(
			'family' => 'Outfit',
			'style'  => '700',
			'size'   => '16',
			'line_height'=>'1',
			'letter_spacing' => '0px',
		),
		'typography_buttons_loadmore' => array(
			'family' => 'Outfit',
			'style'  => '700',
			'size'   => '16',
			'line_height'=>'1',
			'letter_spacing' => '0px',
		),
		'typography_pagination'	=> array(
			'family' => 'Outfit',
			'style'  => '700',
			'size'   => '16',
			'line_height'=>'1',
			'letter_spacing' => '0px',
		),		
		'typography_bottom_menu' => array(
			'family' => 'Outfit',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'1.5',
			'letter_spacing' => '0px',
		),
		'bottom_background_color_loadmore'	=> '',
		'bottom_background_color_loadmore_bg'	=> '',
		'bottom_background_color_loadmore_hover'	=> '',
		'bottom_background_color_loadmore_bg_hover'	=> '',
		'breadcrumb_enabled' => 1,
		'show_post_paginator' => 1,
		'blog_grid_columns' => 2,
		'post_content_elements' => 'meta,title,excerpt_content',
		'meta_elements' => 'author,comment',
		'blog_archive_exclude' => '',
		'blog_featured_title' => 'Blog Details',
		'sidebar_layout' => 'sidebar-right',
		'blog_archive_layout' => 'blog-list',
		'related_post_style'	=> 'blog-grid',
		'grid_columns_post_related' => 2,
		'number_related_post' => 2,
		'blog_sidebar_list'		  => 'blog-sidebar',	
		'blog_archive_readmore' => 1,
		'blog_archive_post_excepts_length' => 43,
		'blog_archive_readmore_text' => 'Read More ',
		'blog_archive_pagination_style' => 'pager-numeric',
		'blog_posts_per_page'	=> 3,
		'blog_order_by'	=> 'date',
		'blog_order_direction' => 'DESC',
		'page_sidebar_list'	=> 'blog-sidebar',	

		'portfolio_slug' => '',
		'portfolio_name' => '',
		'portfolio_show_filter' => 0,
		'portfolio_grid_columns' => 3,
		'portfolios_number_post'=> 9,
		'portfolio_filter_category_order' => '',
		'portfolio_order_by' => 'author,date,comment',
		'portfolio_order_direction' => 'DESC',
		'portfolio_exclude' => '',
		'portfolios_layout' => 'fullwidth',
		'portfolios_show_post_navigator' => 1,
		'portfolios_show_related' => 0,
		'portfolios_related_grid_columns' => 3,
		'portfolios_sidebar_list' => 'blog-sidebar',
		'portfolio_post_image'	=> THEMESFLAT_LINK . 'images/logo.png',
		'number_related_post_portfolios' => 3,
		'portfolios_featured_title' => 'Portfolio Details',


		'project_number_post'=> 9,

		'services_slug' => '',
		'services_name' => '',
		'services_show_filter' => 0,
		'services_grid_columns' => 2,
		'services_number_post'=> 6,
		'services_archive_pagination_style' => 'pager-numeric',
		'services_filter_category_order' => '',
		'services_order_by' => 'date',
		'services_order_direction' => 'DESC',
		'services_exclude' => '',
		'services_layout' => 'fullwidth',
		'services_sidebar_list' => 'themesflat-custom-sidebar-servicessidebar',
		'services_show_post_navigator' => 0,
		'services_show_related' => 0,
		'services_related_grid_columns' => 3,
		'number_related_post_services' => 3,
		'services_featured_title' => 'Services Details',

		'team_slug' => '',
		'team_name' => '',
		'team_grid_columns' => 4,
		'team_number_post'=> 4,
		'team_archive_pagination_style' => 'pager-numeric',
		'team_order_by' => 'date',
		'team_order_direction' => 'DESC',
		'team_exclude' => '',
		'team_featured_title' => 'Team Details',
		
		'typography_footer' => array(
			'family' => 'Poppins',
			'style'  => '400',
			'size'   => '15',
			'line_height'=>'2',
			'letter_spacing' => '',
		),
		'footer_background_color'	=> '#252c24',
		'footer_title_widget_color' => '#fff',
		'footer_text_color'			=> '#798883',
		'footer_text_color_hover'   => '#e6d54f',
		'footer_widget_areas' => 3,
		'footer_controls' => array('padding-top' => 111, 'padding-bottom' => 77),
		'footer1' => 'footer-1',
		'footer2' => 'footer-2',
		'footer3' => 'footer-3',
		'footer4' => 'footer-4',
		'footer_background_image' => '',
		'footer_image_size' => 'cover',
		'typography_bottom_copyright' => array(
			'family' => 'Poppins',
			'style'  => '400',
			'size'   => '15',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'bottom_background_color'	=> '',
		'bottom_text_color'			=> '#fff',
		'bottom_link_color'         => '#120A21',
		'bottom_text_color_hover'   => '#e6d54f',		
		'layout_version'			=> 'wide',		
		'footer_copyright'			=> 'Copyright © 2022 Graingrower – Agriculture Farming Wordpress Template <a href="https://themeforest.net/user/themesflat/portfolio">Themesflat</a>',
		'enable_smooth_scroll'	=> 0,
		'enable_preload' => 1,
		'preload' => 'preload-6',
		'page_title_styles' => 'parallax',
		'page_title_alignment' => 'center',
		'page_title_video_url' => '',		
		'show_action_box'	=> 0,
		'heading_action_box'	=>	'Get Every Single Updates Newsletter Subscribe',
		'text_action_box'	=>	'Our Newsletter',
		'form_action_box'	=>	'[mc4wp_form id="79"]',
		'action_box_features_image' =>  THEMESFLAT_LINK . 'images/acb-img.png',
        'text_button_action_box'	=> '',
        'action_box_background_image' =>  THEMESFLAT_LINK . '',
        'action_box_background_color' => '#e6d54f',
        'action_box_heading_color' => '#fff',
        'action_box_text_color'	=> '#fff',
        'action_box_button_text_color' => '',
        'action_box_button_background_color' => '',
		'action_box_button_url' => '',
        'show_partner'	=> 1,
		'img_partner' => '',
		'show_number_img_partner_desktop' => 6,
		'show_number_img_partner_tablet' => 4,
		'show_number_img_partner_mobile' => 2,
		'gap_img_partner' => 30,
		'partner_box_controls' => array('padding-top' => 67,'padding-bottom' => 64),
		'partner_box_background_color' => '#f2f7f5',
        'show_footer_info'	=> 0,
        'footer_info_text' => 'Solve Your IT Needs Today!',
		'footer_info_button_url' => '/contact-us',
        'footer_info_button' => 'GET SOLUTIONS',
        //Woo
        'shop_products_per_page' => 12,
        'shop_columns' => 3,
        'shop_layout' => 'sidebar-right',
        'shop_layout_single' => 'fullwidth',
        'related_products' => 1,
        'related_products_columns' => 4,
        'product_featured_title' => 'Product Details',
        'product_style' => 'product-style1'
	);
	return $default[$key];
}